name: Intune - Apply Assignments

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read
  statuses: write
  id-token: write
  actions: read


env:
  REPO_DIR: ${{ github.workspace }}
  ASSIGNMENT_FOLDER: ${{ github.workspace }}/staging/deviceconfiguration/assignments
  ARTIFACT_NAME: artifacts
  EXPORT_FOLDER: ${{ github.workspace }}/staging/deviceconfiguration/assignments/artifacts
  github-token: ${{ secrets.GITHUB_TOKEN }}

jobs:
  apply_assignments:
    runs-on: ubuntu-latest
    environment: GraphApi

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Install Microsoft Graph Modules
        shell: pwsh
        run: |
          Install-Module Microsoft.Graph.Authentication -Force -AllowClobber
          Install-Module Microsoft.Graph.Beta.DeviceManagement -Force -AllowClobber

      # Step 1: Download the merged assignments artifact
      - name: Download merged assignments artifact
        uses: actions/download-artifact@v4
        with:
          name: merged-assignments
          path: ${{ env.EXPORT_FOLDER }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Apply assignments
      - name: Apply Assignments
        shell: pwsh
        run: |
          $token = (az account get-access-token --resource https://graph.microsoft.com | ConvertFrom-Json).accessToken
          Connect-MgGraph -AccessToken (ConvertTo-SecureString $token -AsPlainText -Force)
          Import-Module -Name "${{ env.REPO_DIR }}" -Force
      
          # Path to merged assignments file
          $mergedFilePath = "${{ github.workspace }}/staging/deviceconfiguration/assignments/artifacts/merged-assignments.json"
          Write-Host "Applying assignments from $mergedFilePath"
      
          # Check if the merged file exists
          if (-not (Test-Path $mergedFilePath)) {
            Write-Error "Merged assignment JSON file not found at $mergedFilePath"
            exit 1
          }
      
          # Apply the merged assignments
          Set-IntuneDeviceConfigurationPolicyAssignment -InputFilePath $mergedFilePath
          Write-Host "All assignments applied successfully."
